#!/bin/bash 
sleep 2
clear
echo ""
echo "--------------------------------------------------------------------"
chmod +x /etc/DARKSSH-MANAGER/speedtest-cli
echo ""

echo "--------------------------------------------------------------------"
